import chalk from "chalk";
import * as readline from "readline";
import { writeFileSync, existsSync, mkdirSync } from "fs";
import { join } from "path";

const PROVIDERS = [
  { name: "openai", label: "OpenAI", envVar: "OPENAI_API_KEY", models: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "o1-preview", "o1-mini"] },
  { name: "openrouter", label: "OpenRouter (100+ моделей)", envVar: "OPENROUTER_API_KEY", models: ["openai/gpt-4o", "anthropic/claude-3.5-sonnet", "google/gemini-pro-1.5", "meta-llama/llama-3.1-405b"] },
  { name: "anthropic", label: "Anthropic (Claude)", envVar: "ANTHROPIC_API_KEY", models: ["claude-sonnet-4-20250514", "claude-3-5-haiku-20241022"] },
];

function ask(rl: readline.Interface, question: string): Promise<string> {
  return new Promise((resolve) => {
    rl.question(question, (answer) => resolve(answer.trim()));
  });
}

function askChoice(rl: readline.Interface, question: string, options: string[]): Promise<number> {
  return new Promise((resolve) => {
    console.log(chalk.white(question));
    options.forEach((opt, i) => {
      console.log(chalk.gray(`  ${i + 1}) ${opt}`));
    });
    rl.question(chalk.green("Выбор (номер): "), (answer) => {
      const num = parseInt(answer) - 1;
      if (num >= 0 && num < options.length) {
        resolve(num);
      } else {
        console.log(chalk.red("Неверный выбор, попробуйте снова."));
        resolve(askChoice(rl, question, options));
      }
    });
  });
}

function askNumber(rl: readline.Interface, question: string, defaultVal: number): Promise<number> {
  return new Promise((resolve) => {
    rl.question(chalk.green(`${question} (по умолчанию ${defaultVal}): `), (answer) => {
      if (!answer) { resolve(defaultVal); return; }
      const num = parseFloat(answer);
      if (isNaN(num)) { resolve(defaultVal); return; }
      resolve(num);
    });
  });
}

export async function runSetup(): Promise<void> {
  console.log();
  console.log(chalk.cyan.bold("  ╔═══════════════════════════════════════╗"));
  console.log(chalk.cyan.bold("  ║        ") + chalk.white.bold("nexo-agent setup") + chalk.cyan.bold("            ║"));
  console.log(chalk.cyan.bold("  ║   Первичная настройка проекта         ║"));
  console.log(chalk.cyan.bold("  ╚═══════════════════════════════════════╝"));
  console.log();

  const rl = readline.createInterface({ input: process.stdin, output: process.stdout });

  try {
    // 1. Выбор провайдера
    const providerIdx = await askChoice(rl, "Выберите LLM-провайдер:", PROVIDERS.map((p) => `${p.label} (${p.envVar})`));
    const provider = PROVIDERS[providerIdx];

    console.log(chalk.gray(`\nВыбран: ${provider.label}\n`));

    // 2. API ключ
    const apiKey = await ask(rl, chalk.green(`Введите ${provider.envVar}: `));
    if (!apiKey) {
      console.log(chalk.red("API ключ обязателен!"));
      process.exit(1);
    }

    // 3. Выбор модели
    const modelIdx = await askChoice(rl, "Выберите модель:", provider.models);
    const model = provider.models[modelIdx];

    console.log(chalk.gray(`\nМодель: ${model}\n`));

    // 4. Температура
    const temperature = await askNumber(rl, "Температура (0.0 - 2.0)", 0.7);

    // 5. Максимум токенов
    const maxTokens = await askNumber(rl, "Максимум токенов в ответе", 4096);

    // 6. Уровень логирования
    const logLevelIdx = await askChoice(rl, "Уровень логирования:", ["debug", "info", "warn", "error"]);
    const logLevels = ["debug", "info", "warn", "error"];
    const logLevel = logLevels[logLevelIdx];

    // Сохранение .env
    const envPath = join(process.cwd(), ".env");
    const envLines = [`${provider.envVar}=${apiKey}`];
    if (existsSync(envPath)) {
      console.log(chalk.yellow(`\nФайл .env уже существует, обновляю...`));
    }
    writeFileSync(envPath, envLines.join("\n") + "\n", "utf-8");
    console.log(chalk.green(`✓ .env сохранён`));

    // Сохранение nexo.config.yaml
    const configPath = join(process.cwd(), "nexo.config.yaml");
    const configContent = `# nexo-agent configuration
# Generated by: nexo setup

model: "${model}"
provider: "${provider.name}"
maxTokens: ${maxTokens}
temperature: ${temperature}
logLevel: "${logLevel}"
`;
    writeFileSync(configPath, configContent, "utf-8");
    console.log(chalk.green(`✓ nexo.config.yaml сохранён`));

    // Создание домашней директории
    const homeDir = join(process.env.HOME || process.env.USERPROFILE || ".", ".nexo-agent");
    if (!existsSync(homeDir)) {
      mkdirSync(homeDir, { recursive: true });
      console.log(chalk.green(`✓ Создана директория ${homeDir}`));
    }

    // Итог
    console.log();
    console.log(chalk.cyan.bold("═══════════════════════════════════════════"));
    console.log(chalk.green.bold("  Настройка завершена!"));
    console.log();
    console.log(chalk.white("  Провайдер:  ") + chalk.yellow(provider.label));
    console.log(chalk.white("  Модель:     ") + chalk.yellow(model));
    console.log(chalk.white("  Температура:") + chalk.yellow(String(temperature)));
    console.log(chalk.white("  Токены:     ") + chalk.yellow(String(maxTokens)));
    console.log(chalk.white("  Логирование:") + chalk.yellow(logLevel));
    console.log();
    console.log(chalk.gray("  Запуск: nexo chat"));
    console.log(chalk.cyan.bold("═══════════════════════════════════════════"));
    console.log();

  } finally {
    rl.close();
  }
}
